{
  "models": [
    {
      "title": "DeepSeek Coder",
      "provider": "openai",
      "model": "deepseek-coder",
      "apiBase": "https://api.deepseek.com/v1",
      "apiKey": "sk-ab99d30631374a47a098c0831617e044"
    }
  ],
  "tabAutocompleteModel": {
    "title": "DeepSeek Coder (автодополнение)",
    "provider": "openai",
    "model": "deepseek-coder",
    "apiBase": "https://api.deepseek.com/v1",
    "apiKey": "sk-ab99d30631374a47a098c0831617e044"
  }
}